# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs: 
  - job: Job1
    steps:
      - bash: echo BuildNumber$(Build.BuildId)
      - bash: echo sai1
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents: |
            **/*.yaml
            **/*.tf
          TargetFolder: '$(Build.ArtifactStagingDirectory)'
      - bash: echo sai2
      - bash: ls -R $(Build.ArtifactStagingDirectory)
      - bash: echo sai3
      - script: echo Hello job1 $(MyVariable)
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
  - job : Job2
    steps:
      - script: echo Hello job2
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
- stage: DevDeploy
  dependsOn: Build
  jobs: 
  - job: DevDeployJob1
    steps:
      - script: echo Hello DevDeployJob1
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
- stage: QADeploy
  variables:
    QAVariable: QA
  dependsOn: Build
  jobs: 
  - job: QADeployJob1
    steps:
      - script: echo Hello QADeploy1 $(QAVariable)
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
- stage: ProdDeploy
  dependsOn: 
  - DevDeploy
  - QADeploy
  jobs: 
  - job: ProdDeployJob
    steps:
      - script: echo Hello ProdDeployJob
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'


